# Generated by Django 3.1.2 on 2020-11-26 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('instructions', models.TextField()),
                ('image', models.URLField(max_length=256)),
                ('ease_of_prep', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('prep_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(max_length=256)),
                ('types', models.CharField(max_length=256)),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient')),
            ],
        ),
    ]
